

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."carrito" (
    "id" integer NOT NULL,
    "fecha_actualizacion" timestamp(6) without time zone NOT NULL,
    "session_token" character varying(64),
    "usuario_id" integer
);


ALTER TABLE "public"."carrito" OWNER TO "postgres";


ALTER TABLE "public"."carrito" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."carrito_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."carrito_items" (
    "id" integer NOT NULL,
    "cantidad" integer NOT NULL,
    "carrito_id" integer NOT NULL,
    "producto_id" integer NOT NULL
);


ALTER TABLE "public"."carrito_items" OWNER TO "postgres";


ALTER TABLE "public"."carrito_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."carrito_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categorias" (
    "id" integer NOT NULL,
    "descripcion" character varying(500),
    "nombre" character varying(100) NOT NULL
);


ALTER TABLE "public"."categorias" OWNER TO "postgres";


ALTER TABLE "public"."categorias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categorias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."compras" (
    "id" integer NOT NULL,
    "fecha" timestamp(6) without time zone NOT NULL,
    "numero_factura" character varying(255) NOT NULL,
    "total" double precision NOT NULL,
    "proveedor_id" integer NOT NULL
);


ALTER TABLE "public"."compras" OWNER TO "postgres";


ALTER TABLE "public"."compras" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."compras_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."detalle_compras" (
    "id" integer NOT NULL,
    "cantidad" integer NOT NULL,
    "precio_unitario" double precision NOT NULL,
    "subtotal" double precision NOT NULL,
    "compra_id" integer NOT NULL,
    "producto_id" integer NOT NULL
);


ALTER TABLE "public"."detalle_compras" OWNER TO "postgres";


ALTER TABLE "public"."detalle_compras" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."detalle_compras_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."favoritos" (
    "id" integer NOT NULL,
    "producto_id" integer NOT NULL,
    "usuario_id" integer NOT NULL
);


ALTER TABLE "public"."favoritos" OWNER TO "postgres";


ALTER TABLE "public"."favoritos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."favoritos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notificaciones" (
    "id" integer NOT NULL,
    "fecha" timestamp(6) without time zone NOT NULL,
    "leido" boolean NOT NULL,
    "mensaje" character varying(500) NOT NULL,
    "tipo" character varying(30) NOT NULL,
    "usuario_id" integer NOT NULL
);


ALTER TABLE "public"."notificaciones" OWNER TO "postgres";


ALTER TABLE "public"."notificaciones" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notificaciones_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pagos" (
    "id" integer NOT NULL,
    "estado_pago" character varying(20) NOT NULL,
    "fecha_pago" timestamp(6) without time zone NOT NULL,
    "metodo_pago" character varying(255) NOT NULL,
    "monto" double precision NOT NULL,
    "venta_id" integer NOT NULL,
    CONSTRAINT "pagos_estado_pago_check" CHECK ((("estado_pago")::"text" = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADO'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying])::"text"[]))),
    CONSTRAINT "pagos_metodo_pago_check" CHECK ((("metodo_pago")::"text" = ANY ((ARRAY['EFECTIVO'::character varying, 'YAPE'::character varying, 'TRANSFERENCIA'::character varying, 'TARJETA'::character varying, 'CREDITO'::character varying])::"text"[])))
);


ALTER TABLE "public"."pagos" OWNER TO "postgres";


ALTER TABLE "public"."pagos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pagos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."password_reset_tokens" (
    "id" bigint NOT NULL,
    "codigo" character varying(6) NOT NULL,
    "fecha_expiracion" timestamp(6) without time zone NOT NULL,
    "utilizado" boolean NOT NULL,
    "usuario_id" integer NOT NULL
);


ALTER TABLE "public"."password_reset_tokens" OWNER TO "postgres";


ALTER TABLE "public"."password_reset_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."password_reset_tokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."permisos" (
    "id" integer NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "descripcion" character varying(255) NOT NULL,
    "nombre" character varying(120) NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "modulo" character varying(80) DEFAULT 'General'::character varying NOT NULL
);


ALTER TABLE "public"."permisos" OWNER TO "postgres";


ALTER TABLE "public"."permisos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."permisos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."producto_imagenes" (
    "id" integer NOT NULL,
    "archivo" character varying(255) NOT NULL
);


ALTER TABLE "public"."producto_imagenes" OWNER TO "postgres";


ALTER TABLE "public"."producto_imagenes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."producto_imagenes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."productos" (
    "id" integer NOT NULL,
    "codigo" character varying(255) NOT NULL,
    "descripcion" character varying(255) NOT NULL,
    "nombre" character varying(255) NOT NULL,
    "precio_compra" double precision NOT NULL,
    "precio_venta" double precision NOT NULL,
    "stock" integer NOT NULL,
    "categoria_id" integer NOT NULL,
    "url_imagen" character varying(255),
    "id_imagen" integer
);


ALTER TABLE "public"."productos" OWNER TO "postgres";


ALTER TABLE "public"."productos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."productos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proveedores" (
    "id" integer NOT NULL,
    "email" character varying(255) NOT NULL,
    "nombre" character varying(255) NOT NULL,
    "ruc" character varying(255) NOT NULL,
    "telefono" character varying(255) NOT NULL
);


ALTER TABLE "public"."proveedores" OWNER TO "postgres";


ALTER TABLE "public"."proveedores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proveedores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."role_permiso" (
    "role_id" integer NOT NULL,
    "permiso_id" integer NOT NULL
);


ALTER TABLE "public"."role_permiso" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" integer NOT NULL,
    "nombre" character varying(255) NOT NULL,
    "descripcion" character varying(500)
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuario" (
    "id" integer NOT NULL,
    "email" character varying(100) NOT NULL,
    "password" character varying(255) NOT NULL,
    "username" character varying(50) NOT NULL,
    "rol_id" integer NOT NULL,
    "departamento" character varying(80),
    "direccion" character varying(255),
    "distrito" character varying(80),
    "provincia" character varying(80),
    "referencia" character varying(255),
    "telefono" character varying(20),
    "google_place_id" character varying(255),
    "latitud" double precision,
    "longitud" double precision,
    "dni_ruc" character varying(11),
    "nombre_razon_social" character varying(255)
);


ALTER TABLE "public"."usuario" OWNER TO "postgres";


ALTER TABLE "public"."usuario" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usuario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."venta_detalles" (
    "id" integer NOT NULL,
    "cantidad" integer NOT NULL,
    "precio_unitario" double precision NOT NULL,
    "subtotal" double precision NOT NULL,
    "producto_id" integer NOT NULL,
    "venta_id" integer NOT NULL
);


ALTER TABLE "public"."venta_detalles" OWNER TO "postgres";


ALTER TABLE "public"."venta_detalles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."venta_detalles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ventas" (
    "id" integer NOT NULL,
    "canal" character varying(255) NOT NULL,
    "codigo_recojo" character varying(255),
    "costo_envio" double precision,
    "direccion_entrega" character varying(255),
    "direccion_fiscal" character varying(255),
    "dni" character varying(8),
    "email_comprobante" character varying(100),
    "estado_pago" character varying(20) NOT NULL,
    "estado_pedido" character varying(255) NOT NULL,
    "fecha" "date" NOT NULL,
    "igv" double precision,
    "metodo_pago" character varying(255) NOT NULL,
    "nombre_comprobante" character varying(150),
    "razon_social" character varying(200),
    "ruc" character varying(11),
    "subtotal" double precision,
    "tipo_comprobante" character varying(255) NOT NULL,
    "tipo_entrega" character varying(255) NOT NULL,
    "total" double precision NOT NULL,
    "cliente_id" integer,
    "usuario_id" integer,
    CONSTRAINT "ventas_canal_check" CHECK ((("canal")::"text" = ANY ((ARRAY['PRESENCIAL'::character varying, 'WEB'::character varying])::"text"[]))),
    CONSTRAINT "ventas_estado_pago_check" CHECK ((("estado_pago")::"text" = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADO'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying])::"text"[]))),
    CONSTRAINT "ventas_estado_pedido_check" CHECK ((("estado_pedido")::"text" = ANY ((ARRAY['PENDIENTE'::character varying, 'EN_PROCESO'::character varying, 'LISTO_PARA_RECOJO'::character varying, 'EN_CAMINO'::character varying, 'ENTREGADO'::character varying])::"text"[]))),
    CONSTRAINT "ventas_metodo_pago_check" CHECK ((("metodo_pago")::"text" = ANY ((ARRAY['EFECTIVO'::character varying, 'YAPE'::character varying, 'TRANSFERENCIA'::character varying, 'TARJETA'::character varying, 'CREDITO'::character varying])::"text"[]))),
    CONSTRAINT "ventas_tipo_comprobante_check" CHECK ((("tipo_comprobante")::"text" = ANY ((ARRAY['TICKET'::character varying, 'BOLETA'::character varying, 'FACTURA'::character varying])::"text"[]))),
    CONSTRAINT "ventas_tipo_entrega_check" CHECK ((("tipo_entrega")::"text" = ANY ((ARRAY['FAST_LANE'::character varying, 'DELIVERY'::character varying, 'PRESENCIAL'::character varying])::"text"[])))
);


ALTER TABLE "public"."ventas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ventas_entrega" (
    "id" integer NOT NULL,
    "codigo_recojo" character varying(255),
    "direccion" character varying(255),
    "distrito" character varying(255),
    "referencia" character varying(255),
    "tipo_entrega" character varying(255) NOT NULL,
    "venta_id" integer NOT NULL,
    CONSTRAINT "ventas_entrega_tipo_entrega_check" CHECK ((("tipo_entrega")::"text" = ANY ((ARRAY['FAST_LANE'::character varying, 'DELIVERY'::character varying, 'PRESENCIAL'::character varying])::"text"[])))
);


ALTER TABLE "public"."ventas_entrega" OWNER TO "postgres";


ALTER TABLE "public"."ventas_entrega" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ventas_entrega_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."ventas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ventas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."carrito_items"
    ADD CONSTRAINT "carrito_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."carrito"
    ADD CONSTRAINT "carrito_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categorias"
    ADD CONSTRAINT "categorias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."compras"
    ADD CONSTRAINT "compras_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."detalle_compras"
    ADD CONSTRAINT "detalle_compras_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."favoritos"
    ADD CONSTRAINT "favoritos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notificaciones"
    ADD CONSTRAINT "notificaciones_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pagos"
    ADD CONSTRAINT "pagos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."password_reset_tokens"
    ADD CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."permisos"
    ADD CONSTRAINT "permisos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."producto_imagenes"
    ADD CONSTRAINT "producto_imagenes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "productos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proveedores"
    ADD CONSTRAINT "proveedores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."role_permiso"
    ADD CONSTRAINT "role_permiso_pkey" PRIMARY KEY ("role_id", "permiso_id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "uk484h38jewxsitps4lhvlqbmqw" UNIQUE ("id_imagen");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "uk5171l57faosmj8myawaucatdw" UNIQUE ("email");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "uk863n1y3x0jalatoir4325ehal" UNIQUE ("username");



ALTER TABLE ONLY "public"."ventas_entrega"
    ADD CONSTRAINT "ukcobibox83obl9cyv8evdyqy8c" UNIQUE ("venta_id");



ALTER TABLE ONLY "public"."pagos"
    ADD CONSTRAINT "ukg4qf7r87l9uvptf9ec14c9sv9" UNIQUE ("venta_id");



ALTER TABLE ONLY "public"."carrito"
    ADD CONSTRAINT "ukl0k5f5n9g4mmomxvct8nftc3l" UNIQUE ("session_token");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "ukldv0v52e0udsh2h1rs0r0gw1n" UNIQUE ("nombre");



ALTER TABLE ONLY "public"."permisos"
    ADD CONSTRAINT "ukmd9j2tw7h6dxprrypo0itpnyp" UNIQUE ("nombre");



ALTER TABLE ONLY "public"."favoritos"
    ADD CONSTRAINT "ukovhcwkc0487ugetvikcdu71sm" UNIQUE ("usuario_id", "producto_id");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "usuario_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."venta_detalles"
    ADD CONSTRAINT "venta_detalles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ventas_entrega"
    ADD CONSTRAINT "ventas_entrega_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ventas"
    ADD CONSTRAINT "ventas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."favoritos"
    ADD CONSTRAINT "fk197jjv60qkknc6s6uvnel1nr9" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "fk2cmn7p6dt3xdraj5q4xjmdd8u" FOREIGN KEY ("id_imagen") REFERENCES "public"."producto_imagenes"("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "fk2fwq10nwymfv7fumctxt9vpgb" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias"("id");



ALTER TABLE ONLY "public"."password_reset_tokens"
    ADD CONSTRAINT "fk3gbtnfw48vok3vy1lqjm67wea" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id");



ALTER TABLE ONLY "public"."role_permiso"
    ADD CONSTRAINT "fk3qf3opsf027igh4e7kdigtg7b" FOREIGN KEY ("permiso_id") REFERENCES "public"."permisos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ventas"
    ADD CONSTRAINT "fk53tga44h4mq5iu4plfji4e7h" FOREIGN KEY ("cliente_id") REFERENCES "public"."usuario"("id");



ALTER TABLE ONLY "public"."carrito_items"
    ADD CONSTRAINT "fk5533tt6sc1y47s9gtk4vsgweb" FOREIGN KEY ("carrito_id") REFERENCES "public"."carrito"("id");



ALTER TABLE ONLY "public"."venta_detalles"
    ADD CONSTRAINT "fk6oe5rpuq8yx6emqvsfb50nipb" FOREIGN KEY ("venta_id") REFERENCES "public"."ventas"("id");



ALTER TABLE ONLY "public"."carrito"
    ADD CONSTRAINT "fk8ymop2vbmxmjq6ehl5vj3hpqm" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id");



ALTER TABLE ONLY "public"."role_permiso"
    ADD CONSTRAINT "fk9jh4r3fmyt76lchmih1xced0v" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."compras"
    ADD CONSTRAINT "fkabfd3b61ss0f7ebhao6evn5ec" FOREIGN KEY ("proveedor_id") REFERENCES "public"."proveedores"("id");



ALTER TABLE ONLY "public"."notificaciones"
    ADD CONSTRAINT "fkc3svgi1f8am7ttyaxk652q0a" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id");



ALTER TABLE ONLY "public"."venta_detalles"
    ADD CONSTRAINT "fke1gvs8gted01cefvq4310ir99" FOREIGN KEY ("producto_id") REFERENCES "public"."productos"("id");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "fkehtf9w9752mgyxuamu1649laq" FOREIGN KEY ("rol_id") REFERENCES "public"."roles"("id");



ALTER TABLE ONLY "public"."carrito_items"
    ADD CONSTRAINT "fkfaxp2h71mb51yhv0atg107irl" FOREIGN KEY ("producto_id") REFERENCES "public"."productos"("id");



ALTER TABLE ONLY "public"."ventas"
    ADD CONSTRAINT "fkn7rj3vt9pew8ahxt4f0qn9f6y" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id");



ALTER TABLE ONLY "public"."detalle_compras"
    ADD CONSTRAINT "fkobinn960qd4nxk1b3b0n6aps1" FOREIGN KEY ("producto_id") REFERENCES "public"."productos"("id");



ALTER TABLE ONLY "public"."pagos"
    ADD CONSTRAINT "fkr2gojgwqy0othfw6qnrncedj3" FOREIGN KEY ("venta_id") REFERENCES "public"."ventas"("id");



ALTER TABLE ONLY "public"."favoritos"
    ADD CONSTRAINT "fkrxdxytf48cr005vej8540b0rr" FOREIGN KEY ("producto_id") REFERENCES "public"."productos"("id");



ALTER TABLE ONLY "public"."detalle_compras"
    ADD CONSTRAINT "fks7ksdchwhuo5bv58t28iti0f0" FOREIGN KEY ("compra_id") REFERENCES "public"."compras"("id");



ALTER TABLE ONLY "public"."ventas_entrega"
    ADD CONSTRAINT "fkshsp1k59buo3ekfdtnfdeaf8q" FOREIGN KEY ("venta_id") REFERENCES "public"."ventas"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."carrito" TO "anon";
GRANT ALL ON TABLE "public"."carrito" TO "authenticated";
GRANT ALL ON TABLE "public"."carrito" TO "service_role";



GRANT ALL ON SEQUENCE "public"."carrito_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."carrito_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."carrito_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."carrito_items" TO "anon";
GRANT ALL ON TABLE "public"."carrito_items" TO "authenticated";
GRANT ALL ON TABLE "public"."carrito_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."carrito_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."carrito_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."carrito_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categorias" TO "anon";
GRANT ALL ON TABLE "public"."categorias" TO "authenticated";
GRANT ALL ON TABLE "public"."categorias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categorias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categorias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categorias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."compras" TO "anon";
GRANT ALL ON TABLE "public"."compras" TO "authenticated";
GRANT ALL ON TABLE "public"."compras" TO "service_role";



GRANT ALL ON SEQUENCE "public"."compras_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."compras_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."compras_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."detalle_compras" TO "anon";
GRANT ALL ON TABLE "public"."detalle_compras" TO "authenticated";
GRANT ALL ON TABLE "public"."detalle_compras" TO "service_role";



GRANT ALL ON SEQUENCE "public"."detalle_compras_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."detalle_compras_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."detalle_compras_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."favoritos" TO "anon";
GRANT ALL ON TABLE "public"."favoritos" TO "authenticated";
GRANT ALL ON TABLE "public"."favoritos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."favoritos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."favoritos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."favoritos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notificaciones" TO "anon";
GRANT ALL ON TABLE "public"."notificaciones" TO "authenticated";
GRANT ALL ON TABLE "public"."notificaciones" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notificaciones_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notificaciones_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notificaciones_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pagos" TO "anon";
GRANT ALL ON TABLE "public"."pagos" TO "authenticated";
GRANT ALL ON TABLE "public"."pagos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pagos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pagos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pagos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."password_reset_tokens" TO "anon";
GRANT ALL ON TABLE "public"."password_reset_tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."password_reset_tokens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."password_reset_tokens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."password_reset_tokens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."password_reset_tokens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."permisos" TO "anon";
GRANT ALL ON TABLE "public"."permisos" TO "authenticated";
GRANT ALL ON TABLE "public"."permisos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."permisos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."permisos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."permisos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."producto_imagenes" TO "anon";
GRANT ALL ON TABLE "public"."producto_imagenes" TO "authenticated";
GRANT ALL ON TABLE "public"."producto_imagenes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."producto_imagenes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."producto_imagenes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."producto_imagenes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."productos" TO "anon";
GRANT ALL ON TABLE "public"."productos" TO "authenticated";
GRANT ALL ON TABLE "public"."productos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."productos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."productos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."productos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proveedores" TO "anon";
GRANT ALL ON TABLE "public"."proveedores" TO "authenticated";
GRANT ALL ON TABLE "public"."proveedores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proveedores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proveedores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proveedores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."role_permiso" TO "anon";
GRANT ALL ON TABLE "public"."role_permiso" TO "authenticated";
GRANT ALL ON TABLE "public"."role_permiso" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuario" TO "anon";
GRANT ALL ON TABLE "public"."usuario" TO "authenticated";
GRANT ALL ON TABLE "public"."usuario" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usuario_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."usuario_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usuario_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."venta_detalles" TO "anon";
GRANT ALL ON TABLE "public"."venta_detalles" TO "authenticated";
GRANT ALL ON TABLE "public"."venta_detalles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."venta_detalles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."venta_detalles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."venta_detalles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ventas" TO "anon";
GRANT ALL ON TABLE "public"."ventas" TO "authenticated";
GRANT ALL ON TABLE "public"."ventas" TO "service_role";



GRANT ALL ON TABLE "public"."ventas_entrega" TO "anon";
GRANT ALL ON TABLE "public"."ventas_entrega" TO "authenticated";
GRANT ALL ON TABLE "public"."ventas_entrega" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ventas_entrega_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ventas_entrega_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ventas_entrega_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ventas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ventas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ventas_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
